// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// matcher_binding.cpp
cpp11::writable::logicals robotstxtr_allowed_text_(std::string body, cpp11::strings url, std::string user_agent);
extern "C" SEXP _robotstxtr_robotstxtr_allowed_text_(SEXP body, SEXP url, SEXP user_agent) {
  BEGIN_CPP11
    return cpp11::as_sexp(robotstxtr_allowed_text_(cpp11::as_cpp<cpp11::decay_t<std::string>>(body), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(url), cpp11::as_cpp<cpp11::decay_t<std::string>>(user_agent)));
  END_CPP11
}
// matcher_binding.cpp
cpp11::writable::integers robotstxtr_matching_line_text_(std::string body, cpp11::strings url, std::string user_agent);
extern "C" SEXP _robotstxtr_robotstxtr_matching_line_text_(SEXP body, SEXP url, SEXP user_agent) {
  BEGIN_CPP11
    return cpp11::as_sexp(robotstxtr_matching_line_text_(cpp11::as_cpp<cpp11::decay_t<std::string>>(body), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(url), cpp11::as_cpp<cpp11::decay_t<std::string>>(user_agent)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_robotstxtr_robotstxtr_allowed_text_",       (DL_FUNC) &_robotstxtr_robotstxtr_allowed_text_,       3},
    {"_robotstxtr_robotstxtr_matching_line_text_", (DL_FUNC) &_robotstxtr_robotstxtr_matching_line_text_, 3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_robotstxtr(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
