# Generated by cpp11: do not edit by hand

robotstxtr_collect_directives_ <- function(body) {
  .Call(`_robotstxtr_robotstxtr_collect_directives_`, body)
}

robotstxtr_allowed_text_ <- function(body, url, user_agent) {
  .Call(`_robotstxtr_robotstxtr_allowed_text_`, body, url, user_agent)
}

robotstxtr_matching_line_text_ <- function(body, url, user_agent) {
  .Call(`_robotstxtr_robotstxtr_matching_line_text_`, body, url, user_agent)
}
